remote_theme: jeffreytse/jekyll-theme-yat
title: Sunny's Confectionary and Computer Science Emporium  

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - home:
      heading: "Sunny's Confectionary and Computer Science Emporium  "
      subheading: "Her favoritte recipes all in one place"
      banner: https://www.dreamstime.com/illustration/kitchen-watercolor.html

