remote_theme: jeffreytse/jekyll-theme-yat
title: Sunny's Confectionary and Computer Science Emporium  

defaults:
  home:
      heading: "Sunny's Confectionary and Computer Science Emporium  "
      subheading: "Her favorite recipes all in one place"
      banner: /banner.jpeg
      
markdown: kramdown
kmarkdown:
  parse_block_html: "true"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

