remote_theme: jeffreytse/jekyll-theme-yat
title: Sunny's Confectionary and Computer Science Emporium  
subtitle: Sunny's favorite recipes all in one place 
defaults:
  - scope:
      path: ""
    values:
      layout: default
